version: "3"
services:
  mongo:
    image: "mongo"
    ports:
      - 27017:27017
  web:
    build: .
    ports:
      - "3000:3001"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/test
    links:
      - mongo
    depends_on:
      - mongo
    volumes:
      - .:/starter
      - /starter/node_modules
